config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]

  resources :products, only: [:index ,:show, :new, :create, :destroy] do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :status, default: false
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :product_skills, dependent: :destroy
  has_many :skills, through: :product_skills

  mount_uploader :photo, PhotoUploader
  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true

  geocoded_by :city
  after_validation :custom_geocode, if: :will_save_change_to_city?

  def custom_geocode
    self.latitude = 45.5017 + (rand / 100)
    self.longitude = -73.5673 + (rand / 100)
  end


  def fake_address
    address = [
      "2 Cemetery St. Laurentides-Sud",
      "57 Mulberry St. Ponoka",
      "67 Henry Smith Court Taber",
      "8519 Beaver Ridge Ave, QC",
      "860 Sunset Drive Orillia",
      "99 College Road Florenceville",
      "341 South St Paul St. Région",
      "919 South Brook Ave. Kimberley",
      "9806 Old York Street Kings, QC",
      "95 Van Dyke Dr. Tour de la Bours"
    ]
    return address.sample(1).join(" ")
  end
end

app/models/product_skill.rb
class ProductSkill < ApplicationRecord
  belongs_to :product
  belongs_to :skill

  # validates_uniqueness_of :product_id, scope: [:skill_id]
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :product_skills
  has_many :products, through: :product_skills
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products, through: :bookings
  has_many :products, dependent: :destroy
  has_many :bookings
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # def new
  #   @booking = Booking.new
  #   @product = Product.find(params[:product_id])
  # end

  def create
    @product = Product.find(params[:product_id])
    @booking = Booking.new(booking_params)
    @booking.product = @product
    @booking.user = current_user
    @booking.save
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to users_show_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.delete

    redirect_to user_path(current_user)
  end

  private
  def booking_params
    params.require(:booking).permit(:status, :startdate, :enddate, :product_id, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @skills = Skill.all
    @products = Product.all
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    # @products = Product.all
    @products = Skill.find_by(name: params[:skill]).products
    @skill = Skill.find_by(name: params[:skill])

    @products_address = @products.geocoded

    @markers = @products_address.map do |product|
      {
        lat: product.latitude,
        lng: product.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { product: product })
      }
    end
  end

  def show
    @product = Product.find(params[:id])
    @booking = Booking.new
    @markers = [{
        lat: @product.latitude,
        lng: @product.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { product: @product })
      }]
  end

#CREATE-----------------------------------------
  def new
    @product = Product.new
    @skills = Skill.all
  end

  def create
    @product = Product.new(product_params)

    @product.user = current_user
    if @product.save
      params[:skills].keys.each do |skill_id|
        ProductSkill.create(product: @product, skill_id: skill_id)
      end
      redirect_to product_path(@product)
    else
      render :new
    end
  end

#DESTROY----------------------------------------
  def destroy
    @product = Product.find(params[:id])
    # @product.skills.delete_all
    if @product.destroy
      respond_to do |format|
        format.html { redirect_to user_path current_user }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      head :no_content
    end
  end
#EXTRA------------------------------------------
  private

  def product_params
    params.require(:product).permit(:name, :booking, :price, :city, :photo_cache, :photo, skill_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = current_user
#My Product -------------------
    @my_products = user.products
#MY Product Bookings---------------
    @my_bookings = Booking.joins(:product).where(products: { user: user })
    @pending_bookings = @my_bookings.select { |b| b.status == "Pending" }
    @confirmed_bookings = @my_bookings.select { |b| b.status == "Confirmed" }
#MY Bookings Ive made------------------
    @bookings_ive_made = current_user.bookings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for([product, booking], remote: true) do |f| %>
  <%= f.input :startdate, as: :date, html5: true %>
  <%= f.input :enddate, as: :date, html5: true %>
  <%= f.submit "", style: "display: none;", id: "product-booking-create" %>
<% end %>

<%= render "products/rocketbutton" %>

app/views/bookings/edit.html.erb
<h1>CONFIRM OR REFUSE</h1>



<%= simple_form_for(@booking) do |f| %>
  <%= f.input :status%>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>👫 Borrow Me 👫</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<% mens = @products.where({gender: "male"}).first(3) %>
<% womens = @products.where({gender: "female"}).first(3) %>

<div class="banner-container">
  <div class="skw-pages">
    <div class="skw-page skw-page-1 active">
      <div class="skw-page__half skw-page__half--left">
        <div class="skw-page__skewed">
          <div class="skw-page__content"></div>
        </div>
      </div>
      <div class="skw-page__half skw-page__half--right">
        <div class="skw-page__skewed">
          <div class="skw-page__content">

            <% if user_signed_in? %>
              <div class="container_main">
                <h2 class="skw-page__heading"> Hello, <%= current_user.email.split("@").first %> </h2>
                <h2>rent someone today!</h2>
                <p class="skw-page__description">Change your life</p>
              </div>
            <% else %>
              <h2 class="skw-page__heading"> Rent someone today</h2>
              <p class="skw-page__description">Change your life</p>
            <% end %>



          </div>
        </div>
      </div>
    </div>
    <div class="skw-page skw-page-2">
      <div class="skw-page__half skw-page__half--left">
        <div class="skw-page__skewed">
          <div class="skw-page__content">
            <h2 class="skw-page__heading">Cooking</h2>
            <p class="skw-page__description">Taste the World</p>
          </div>
        </div>
      </div>
      <div class="skw-page__half skw-page__half--right">
        <div class="skw-page__skewed">
          <div class="skw-page__content"></div>
        </div>
      </div>
    </div>
    <div class="skw-page skw-page-3">
      <div class="skw-page__half skw-page__half--left">
        <div class="skw-page__skewed">
          <div class="skw-page__content"></div>
        </div>
      </div>
      <div class="skw-page__half skw-page__half--right">
        <div class="skw-page__skewed">
          <div class="skw-page__content">
            <h2 class="skw-page__heading">Talents</h2>
            <p class="skw-page__description">Learn to Sing, Dance and Do Anything!</p>
          </div>
        </div>
      </div>
    </div>
    <div class="skw-page skw-page-4">
      <div class="skw-page__half skw-page__half--left">
        <div class="skw-page__skewed">
          <div class="skw-page__content">
            <h2 class="skw-page__heading">Massage</h2>
            <p class="skw-page__description">Release all the stress!</p>
          </div>
        </div>
      </div>
      <div class="skw-page__half skw-page__half--right">
        <div class="skw-page__skewed">
          <div class="skw-page__content"></div>
        </div>
      </div>
    </div>
    <div class="skw-page skw-page-5">
      <div class="skw-page__half skw-page__half--left">
        <div class="skw-page__skewed">
          <div class="skw-page__content"></div>
        </div>
      </div>
      <div class="skw-page__half skw-page__half--right">
        <div class="skw-page__skewed">
          <div class="skw-page__content">
            <h2 class="skw-page__heading">Book Me</h2>
            <p class="skw-page__description">
              Change your life renting other people!</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



<div class="container">
  <h3> Skill you can choose </h3>
<!--     <div class="col-lg-4"> -->
      <div class="cards-cat">
        <% @skills.each do |skill| %>
          <%= link_to products_path(skill: skill.name) do %>
            <div class="cards-cat-sub" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path skill.photo %>)">
              <p><%= skill.name.capitalize %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
</div>


<div class="container">
  <h3><i class="fas fa-angle-double-right"></i> TOP 3 Boys</h3>
  <div class="cards">
        <% mens.each do |product| %>
          <%= link_to product_path(product) do %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path product.photo, :gravity=>"face", :width=>150, :height=>150, :zoom=>0.7, :crop=>"thumb" %>)">
              <p><%= product.name %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <h3><i class="fas fa-angle-double-right"></i> TOP 3 Girls</h3>
  <div class="cards">
        <% womens.each do |product| %>
          <%= link_to product_path(product) do %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path product.photo, :gravity=>"face", :width=>150, :height=>150, :zoom=>0.7, :crop=>"thumb" %>)">
              <p><%= product.name %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/_info_window.html.erb
<h4><%= product.name %></h4>
<p><%= product.city %></p>

app/views/products/_rocketbutton.html.erb
<a href="/" class="rocket-button">
    <div class="default">Book me now</div>
    <div class="success">
        <svg>
            <use xlink:href="#check">
        </svg>
        <div>Got me!</div>
    </div>
    <div class="animation">
        <div class="rocket">
            <svg>
                <use xlink:href="#rocket">
            </svg>
        </div>
        <div class="smoke">
            <i></i><i></i><i></i><i></i><i></i><i></i>
        </div>
    </div>
</a>

<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 13 11" id="check">
        <polyline stroke="currentColor" points="1 5.5 5 9.5 12 1.5"></polyline>
    </symbol>
    <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 36" id="rocket">
        <path d="M12,0 C18.6666667,8.70175439 19.7777778,19.0350877 15.3333333,31 L8.66666667,31 C4.22222222,19.0350877 5.33333333,8.70175439 12,0 Z" fill="var(--rocket)"></path>
        <path d="M12,0 C5.33333333,8.70175439 4.22222222,19.0350877 8.66666667,31 C6.72222222,17.9473684 7.83333333,7.61403509 12,0 Z" fill="var(--rocket-shadow-left)"></path>
        <path d="M12,0 C18.6666667,8.70175439 19.7777778,19.0350877 15.3333333,31 C17.2777778,17.9473684 16.1666667,7.61403509 12,0 Z" fill="var(--rocket-shadow-right)"></path>
        <path d="M22.2399372,27.25 C21.2403105,25.558628 19.4303122,23.808628 16.21,22 L15,31 L17.6512944,31 C18.2564684,31 18.8216022,31.042427 19.1572924,31.5292747 L21.7379379,35.271956 C22.0515593,35.7267976 22.5795404,36 23.1449294,36 C23.5649145,36 23.9142153,35.7073938 23.9866527,35.3215275 L24,35.146217 L23.9987214,35.1196135 C23.7534506,31.4421183 23.1671892,28.8189138 22.2399372,27.25 Z" fill="var(--rocket-wing-right)"></path>
        <path d="M1.76006278,27.25 C2.75968951,25.558628 4.56968777,23.808628 7.79,22 L9,31 L6.34870559,31 C5.74353157,31 5.17839777,31.042427 4.84270762,31.5292747 L2.2620621,35.271956 C1.94844071,35.7267976 1.42045963,36 0.855070627,36 C0.435085457,36 0.0857846604,35.7073938 0.0133472633,35.3215275 L0,35.146217 L0.00127855763,35.1196135 C0.24654935,31.4421183 0.832810758,28.8189138 1.76006278,27.25 Z" fill="var(--rocket-wing-left)"></path>
        <circle fill="var(--rocket-window-shadow)" cx="12" cy="12" r="3"></circle>
        <circle fill="var(--rocket-window)" cx="12" cy="12" r="2.5"></circle>
        <path d="M15.6021597,5.99977504 L8.39784027,5.99977504 C8.54788101,5.6643422 8.70496315,5.3309773 8.86908669,4.99968036 L15.1309133,4.99968036 C15.2950369,5.3309773 15.452119,5.6643422 15.6021597,5.99977504 Z" fill-opacity="0.3" fill="var(--rocket-line)"></path>
    </symbol>
</svg>
        

app/views/products/destroy.js.erb
productLi = document.querySelector("#product-id-<%= @product.id %>");
productLi.remove();

app/views/products/index.html.erb
 <div class="card-top" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path @skill.photo %>)">
  <%= params[:skill].capitalize %>
 </div>

<div class="container">
   <div
    id="map"
    style="width: 100%;
    height: 300px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
   <div class="card-skills-grid">
    <% @products.each do |product| %>
      <div class="bm-card-product">
        <%= cl_image_tag(product.photo) %>
        <div class="bm-card-product-info">
          <div>
            <p class="name"><%= product.name  %>
              <% if (product.gender == "male") %>
              <i class="fas fa-mars"></i>
            <% else  %>
              <i class="fas fa-venus"></i>
            <% end %>
            </p>
            <p><i class="fas fa-city"></i><%= product.fake_address  %></p>
            <p><i class="fas fa-donate"></i><%= product.price  %> /hour</p>
          </div>
          <div>
            <%= link_to "Book now", product_path(product), class: "btn btn-primary btn-absolute" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
  <div class="new-create-page mx-auto">
    <div class="new-create-title">
      <h1><strong>New Human!</strong></h1>
    </div>

    <%= simple_form_for(@product) do |f| %>
      <%= f.input :name%>
      <%= f.input :photo %>
      <%= f.input :price %>
      <%= f.input :city %>
      <%= f.input :gender, as: :radio_buttons, collection: ['male', 'female']%>
      <hr>
      <%#= f.association :skills  %>
      <div class="skills-name-new-page">
        <h2><strong>Skills</strong></h2>
      </div>
      <hr>
      <div class="d-flex justify-content-around">
        <div>
          <% @skills.first(4).each do |skill| %>
            <div class="form-controll">
              <%= check_box_tag "skills[#{skill.id}]" %>
              <%= label_tag skill.name%>
            </div>
          <% end %>
        </div>
        <div>
          <% @skills.last(4).each do |skill| %>
            <div class="form-controll">
              <%= check_box_tag "skills[#{skill.id}]" %>
              <%= label_tag skill.name%>
            </div>
          <% end %>
        </div>
      </div>
      <%= f.input :photo_cache, as: :hidden %>
      <div class="new-create-cancel-button justify-content-between" style="text-align: center;">
        <%= f.submit class: "btn btn-primary"%> <%= link_to 'Cancel', user_path(current_user), class: "btn btn-danger" %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="container-fluid">

  <div class="row full-page-card">
    <div class="col-8">
      <%= cl_image_tag @product.photo , class:"photo-tag"%>
    </div>
    <div class="col-4 card-show-info">
      <div class="product-attribute d-flex justify-content-between" style="padding-top: 20px">
        <h1><%= @product.name %>
          <% if (@product.gender == "male") %>
            <i class="fas fa-mars"></i>
          <% else  %>
            <i class="fas fa-venus"></i>
          <% end %>
        </h1>
        <p class="product-price"><%= @product.price %>$/hour</p>
      </div>
      <div id="booking-new-container">
        <%= render "bookings/form", product: @product, booking: @booking %>
      </div>
      <div>
        <button class="rate-me-button"> rate me!</button>
      </div>
      <hr>
      <div class="product-attribute d-flex justify-content-between">
      <p><strong>Skills</strong></p>
        <p><% @product.skills.each do |skill| %>
          <%= skill.name %>
        <% end %>
      </p>
      </div>
      <hr>
      <div class="product-attribute d-flex justify-content-between">
        <p><strong>Address</strong></p>
        <p><%= @product.fake_address %></p>
      </div>

      <hr>
      <div class="product-attribute d-flex justify-content-between">
        <p><strong>Released</strong></p>
        <p><%= time_ago_in_words(@product.created_at) %> ago</p>
      </div>
      <hr>
      <div class="product-attribute d-flex justify-content-between">
        <p><strong>Updated</strong></p>
        <p><%= time_ago_in_words(@product.updated_at) %> ago</p>
      </div>
      <hr>
      <div
        id="map"
        style="width: 200;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      ></div>
      <hr>
    </div>
  </div>
</div>

<%#= link_to "hidden", new_product_booking_path(@product), id: "product-booking-new", style: "display: none;" %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <a href="#">About</a>
    <a href="#">Booking</a>
    <a href="#">Contact us</a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dsvdkyjhh/image/upload/v1574178191/logo_hivrhz.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>



  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav mr-auto">

      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, :gravity=>"face", :width=>50, :height=>50, :crop=>"thumb" %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My page ", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Add Product", new_product_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>

      <% end %>
    </ul>
  </div>
</nav>

app/views/users/show.html.erb
  <div class="profile-container">
    <div class="profile-header">
      <h3>Hello, <%= current_user.email.split("@").first %> :)</h3>
    </div>
    <div class="profile-header">

      <%= link_to "Add a Product?", new_product_path, class: "btn btn-primary" %>
    </div>
  </div>

  <div class="space">
    <hr>
      <h2 style="text-align: center;"> <strong>Borrower</strong></h2>
      <p style="text-align: center;"> Your Reservation Status</p>
  </div>

  <div class="profile-container">

    <div class="profile-header">
      <h3>Your Bookings You have made</h3>
    </div>

    <div class="cards-list">

      <% @bookings_ive_made.each do |booking| %>
      <div class="card" >
          <%= cl_image_tag booking.product.photo, :class => "card-img-top", height: 200, width: 200, crop: :fill %>
        <div class = "card-body">
          <li class="card-text">Status : <%= booking.status %></li>
          <li class="card-text">Dates:<%= booking.startdate %> to <%= booking.enddate %></li>
          <%= link_to 'Cancel',  booking_path(booking), method: :delete, class: "btn btn-danger" %>
        </div>
      </div>
      <% end %>
    </div>
      </div>
    </div>
  </div>


  <div class="space">
    <hr>
      <h2 style="text-align: center;"> <strong>Owner</strong></h2>
      <p style="text-align: center;"> Your Product Status</p>
  </div>

  <div class="profile-container">

    <div class="profile-header">
      <h3>All Products</h3>
    </div>
    <div class="cards-list">
    <% current_user.products.each do |product| %>
      <div class="card">
        <%= cl_image_tag product.photo, :class => "card-img-top", height: 200, width: 200, crop: :fill %>
        <div class = "card-body">
          <ul>
            <li>
              <%= link_to 'Details', product_path(product), class: "btn btn-primary" %>
              <%= link_to 'Delete',  product_path(product), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
            </li>
          </ul>
        </div>
      </div>
    <% end %>
  </div>

  </div>


  <div class="profile-container">

    <div class="profile-header">
      <h3>Pending Bookings</h3>
    </div>
  <div class="cards-list">
      <% if @pending_bookings.length > 0 %>
        <% @pending_bookings.each do |booking| %>
        <div class="card">
          <%= cl_image_tag booking.product.photo, :class => "card-img-top", height: 200, width: 200, crop: :fill %>

          <div class = "card-body">
          <li>Status : <%= booking.status %></li>
            <li>
              Dates: <%= booking.startdate %> to <%= booking.enddate %>
            </li>
            <li>
              <%= simple_form_for booking do |f| %>
              <%= f.input :status, as: :hidden, input_html: {value: "Confirmed"} %>
              <%= f.submit "Confirm", class: "btn btn-flat" %>
              <% end %>
              <%= simple_form_for booking do |f| %>
              <%= f.input :status, as: :hidden, input_html: {value: "Delcined"} %>
              <%= f.submit "Decline", class: "btn btn-danger" %>
              <% end %>
            </li>
          </div>
        </div>
      <% end %>
    <% end %>
    </div>
  </div>


  <div class="profile-container">

    <div class="profile-header">
      <h3>Confirmed Bookings</h3>
    </div>

  <div class="cards-list">

      <% @confirmed_bookings.each do |booking| %>
        <div class="card" >
        <%= cl_image_tag booking.product.photo, :class => "card-img-top", height: 200, width: 200, crop: :fill %>
        <div class = "card-body">
          <li class="card-text"> Status : <%= booking.status %></li>
          <li class="card-text"> Dates:<%= booking.startdate %> to <%= booking.enddate %></li>
          <%= link_to 'Delete',  booking_path(booking), method: :delete, class: "btn btn-danger" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>